config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  root 'static_pages#home'
  get '/home',    to: 'static_pages#home'
  get "current/courses" => "courses#current"
  get '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users 
  resources :courses do
    member do
      post :upvote
      post :downvote
    end
  end

  resources :categories

  resources :locations
 
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to Your Course App</h1>

  <h2>This is the home page for the RAD Assignment 2</h2>

  <% if !logged_in? %>

    <%= link_to signup_path, class: "btn btn-lg btn-danger" do %>
      <span class="glyphicon glyphicon-cog"></span>
      Sign up now!
    <% end %>
</div>
<div class="container">
  <div class="col-md-4">
    <p id="home-page-nav-title"><b>View Course as Guest User</b></p>
    <p id="home-page-nav-context">Browse and view courses as a guest and sign up later</p>
    <%= link_to courses_path, class: "btn btn-lg btn-success" do %>
      <span class="glyphicon glyphicon glyphicon-book"></span>
      Browse all courses
    <% end %>
  </div>
  <div class="col-md-4">
    <p id="home-page-nav-title"><b>Sign in to your account</b></p>
    <p id="home-page-nav-context">Update your courses, rate courses, view coordinator informations</p>
    <%= link_to login_path, class: "btn btn-lg btn-success" do %>
      <span class="glyphicon glyphicon glyphicon-log-in"></span>
      Log In to your account
    <% end %>
  </div>
  
  <% else %>
  
    <%= link_to  courses_path, class: "btn btn-lg btn-success" do %>
      <span class="glyphicon glyphicon glyphicon-book"></span>
      Browse all courses
    <% end %>
  
  <% end %>
  
</div>