config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  root 'static_pages#home'
  get '/home',    to: 'static_pages#home'
  get "current/courses" => "courses#current"
  get '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users 
  resources :courses do
    member do
      post :upvote
      post :downvote
    end
  end

  resources :categories

  resources :locations
 
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container jumbotron col-md-12">
    
    <div class="col-md-3">
      <p id="footer-nav-title"><b>Contact us</b></p >
      <form action="#" id="footer-contact-form">
        <input type="name" class="form-control" id="name" placeholder="Name" name="name">
        <input type="email" class="form-control" id="email" placeholder="Email" name="email">
        <textarea class="form-control" rows="5" id="comment" placeholder="Message"></textarea>
        <button type="submit" class="btn btn-link pull-right">Send</button>
      </form>
      <div id="footer-contact-info">
        <p>Tel: 0123456789</p >
        <p>Fax: 0123456</p >
        <p>junliang.jiang@rmit.edu.au</p >
      </div>
    </div>
    
    <div class="col-md-3">
      <p id="footer-nav-title"><b>General inquires</b></p >
      <div>
        <%= link_to "Andy Song", '#' %>
        <br>
        <%= link_to "Junliang Jiang", '#' %>
        <br>
        <%= link_to "Ali", '#' %>
      </div>
    </div>
    
    <div class="col-md-3">
      <p id="footer-nav-title"><b>Useful links</b></p >
      <div>
        <%= link_to "RMIT Course", 'https://www.rmit.edu.au/about/our-education/academic-schools/global-urban-and-social-studies/our-teaching-areas/our-programs-and-courses' %>
        <br>
        <%= link_to "RMIT Help Desk", 'https://www.rmit.edu.au/contact/online-enquiries/local-student-enquiries' %>
        <br>
        <%= link_to "RMIT International", 'https://www.rmit.edu.au/study-with-us/international-students' %>
      </div>
    </div>
    
    <div class="col-md-3">
      <p id="footer-nav-title"><b>Media</b></p >
      <div>
        <%= link_to "Youtube", 'https://www.youtube.com/' %>
        <br>
        <%= link_to "Twitter", 'https://twitter.com/' %>
        <br>
        <%= link_to "Facebook", 'https://www.facebook.com/' %>
        <br>
        <%= link_to "Instagram", 'https://www.instagram.com/' %>
        <br>
        <%= link_to "Skype", 'https://www.skype.com/' %>
      </div>
    </div>
    
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="container">
  <% if logged_in? %>
    <%= link_to "YOURCOURSE", current_courses_path, class: "btn btn-info", id: "logo" %>
   <% end %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown" id="header-right-margin">
          <a href="#" class="dropdown-toggle btn btn-info" data-toggle="dropdown">
            <span class="glyphicon glyphicon-sort-by-alphabet"></span> Category <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <% Category.all.each do |c| %>
              <li><%= link_to c.name, courses_path(course_filters(:category_id => c.id)),  :class => "btn btn-default btn-group #{(params[:category_id].to_i == c.id)? "active" : ""}" %></li>
            <% end %>
            <hr>
            <li><%= link_to "Create category", new_category_path %></li>
          </ul>
        </li>
        <li class="dropdown" id="header-right-margin">
          <a href="#" class="dropdown-toggle btn btn-info" data-toggle="dropdown">
            <span class="glyphicon glyphicon-send"></span> Location <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
           <% Location.all.each do |l| %>
              <li><%= link_to l.name, courses_path(course_filters(:location_id => l.id)),  :class => "btn btn-default btn-group #{(params[:location_id].to_i == l.id)? "active" : ""}" %></li>
            <% end %>
             <hr>
            <li><%= link_to "Create location", new_location_path %></li>
          </ul>
        </li>
      
      <% if logged_in? %>
      
        <li>  
             <%= link_to new_course_path, class: "btn btn-info", id: "header-right-margin" do %>
              <span class="glyphicon glyphicon-file"></span>
              new course
          <% end %>
        </li>
        
        <li class="dropdown" id="header-right-margin-aside">
          <a href="#" class="dropdown-toggle btn btn-danger" data-toggle="dropdown">
            <%= current_user[:name] %> <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "View Profile", current_user %></li>
            <li><%= link_to "Edit Profile", edit_user_path(:user) %></li> 
            <li class="divider"></li>
            <li>
              <%= link_to "Logout", logout_path, method: :delete %>
            </li>
          </ul>
        </li>
        <% else %>
        <li>
          <%= link_to login_path, class: "btn btn-info", id: "header-right-margin-aside" do %>
            <span class="glyphicon glyphicon glyphicon-log-in"></span>
            Log In
          <% end %>
        </li>
        <% end %>
        
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%# <%= render "layouts/flashes" %> 
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>